### PR TITLE
Fix breadcrumbs - 'alv' to 'Alv'. Closes #440

### LINKED ISSUE #440: Jobbe i alv breadcrumb - add capital letter for "Alv"

### PR DESCRIPTION
**Pull request by mikkelcodes**

### CODE REVIEW

File: packages/website/src/components/breadcrumb/index.jsx [hunk 1]
```diff
@@ -17,6 +17,7 @@ const Breadcrumb = ({ path }) => {
         }
       }
       if (el === 'vi-tilbyr') formattedEl = 'Vi tilbyr';
+      if (el === 'jobbe-i-alv') formattedEl = 'Jobbe i Alv';
```
Comment (TheKnarf) [inline packages/website/src/components/breadcrumb/index.jsx:20]: Maybe we could somehow refactor this file to have less if-sentences? Perhaps be more controlled by the CMS or something?

Comment (mikkelcodes) [reply packages/website/src/components/breadcrumb/index.jsx:20]: I agree

Comment (mikkelcodes) [reply packages/website/src/components/breadcrumb/index.jsx]: I've clean up a little bit in the current version. I propose I make a separate issue on this and revisit it when I work on the shared component library

**Review by TheKnarf — APPROVED** [review]
