### PR TITLE
fix video playback safari bug. Closes #478

### LINKED ISSUE #478: Make employee youtube videos play on safari

### PR DESCRIPTION
**Pull request by mikkelcodes**

### CODE REVIEW

File: packages/website/src/components/employeeBio/index.js [hunk 1]
```diff
@@ -143,3 +144,13 @@ const Fallback = ({ src, slug }) => (
     src={src}
   />
 );
+
+<iframe
```
Comment (TheKnarf) [inline packages/website/src/components/employeeBio/index.js:148]: What's the point of this iframe? Seems like it have an hardcoded `src`.

File: packages/website/src/components/employeeBio/index.js [hunk 2]
```diff
@@ -126,13 +126,14 @@ const Webm = ({ src }) => (
     <source type="video/webm" src={src} />
   </video>
 );
-const Youtube = ({ src, slug }) => (
+const Youtube = ({ slug, ytVideoId }) => (
   <iframe
     className="h-60vw sm:h-80 w-screen sm:w-140 seven:w-140 mr-0"
     title={slug}
-    src={`${src}?autoplay=1&mute=0&enablejsapi=1`}
+    src={`https://www.youtube.com/embed/${ytVideoId}
```
Comment (TheKnarf) [inline packages/website/src/components/employeeBio/index.js:133]: Maybe add inn `autoplay` and `mute` as options for the component with a default value?

**Review by TheKnarf — APPROVED** [review]

File: packages/website/src/components/employeeBio/index.js (hunk 2 above)
Comment (mikkelcodes) [reply packages/website/src/components/employeeBio/index.js:133]: I'll create an issue on that.
